# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='', verbose_name='Документ')),
                ('extension', models.CharField(max_length=10, verbose_name='Расширение')),
                ('dateOfModification', models.DateTimeField(verbose_name='Дата изменение')),
            ],
            options={
                'ordering': ['-dateOfModification'],
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('regID', models.CharField(default='', max_length=300)),
                ('departmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.Department')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserToDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('doc', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='documents',
            field=models.ManyToManyField(to='Documents.Document', verbose_name='Документы'),
        ),
    ]
