# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20180201_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
