# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
