# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_auto_20180210_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='documents',
        ),
        migrations.DeleteModel(
            name='UserToDoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departmen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
