# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_auto_20180228_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=200)),
            ],
        ),
    ]
